name: build_on_push

on:
  push:
    branches: [ "main", "develop_branch", "streamlogic" ]
  pull_request:
    branches: [ "main", "develop_branch" ]
  workflow_dispatch:

jobs:
  mcu_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi
          pip install --user nrfutil intelhex

      - name: Bootstrap the dependencies
        run: |
          git submodule init nrfx
          git submodule init micropython
          git submodule update --recursive
          make -C micropython/ports/nrf/ submodules

      - name: Build the firmware and issue a release
        run: |
          make -C port

      - name: Upload release.hex
        uses: actions/upload-artifact@v3
        with:
          name: firmware.hex
          path: port/build/firmware.hex
          retention-days: 5

      - name: Upload firmware.zip
        uses: actions/upload-artifact@v3
        with:
          name: firmware.zip
          path: port/build/firmware.zip
          retention-days: 5

      - name: Upload application.map
        uses: actions/upload-artifact@v3
        with:
          name: application.map
          path: port/build/application.map
          retention-days: 5
